'use client';
import {useEffect,useState,useRef} from 'react';
import {Activity,ArrowLeft,ArrowRight,Bike,CalendarDays,ChartNoAxesCombined,Check,Clock3,Footprints,Moon,Save,Sun,Sunrise,NotebookPen,LockKeyhole,RefreshCw,LogOut} from 'lucide-react';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Checkbox} from '@/components/ui/checkbox';
import {periods,exercises,activities,Day,today,blank,total,painRange,dateLabel,validDay} from '@/lib/records';
const icons=[Sunrise,Sun,Moon];
declare const __RECORD_API_BASE__:string|undefined;
const apiBase=typeof __RECORD_API_BASE__==='string'?__RECORD_API_BASE__:'';
export default function Journal(){
 const [day,setDay]=useState<Day>(()=>blank(today()));
 const [view,setView]=useState('daily'); const [records,setRecords]=useState<Day[]>([]);
 const [accessCode,setAccessCode]=useState('');const [canEdit,setCanEdit]=useState(false);const credential=useRef('');
 function authHeaders():Record<string,string>{return credential.current?{Authorization:`Bearer ${credential.current}`}:{ };}
 const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [dirty,setDirty]=useState(false);const [error,setError]=useState('');const [saved,setSaved]=useState(false);const [auth,setAuth]=useState(false);const [ready,setReady]=useState(false);
 async function load(code?:string){setLoading(true);setError('');if(code!==undefined)credential.current=code.trim();try{const res=await fetch(`${apiBase}/api/records`,{cache:'no-store',headers:authHeaders()});if(res.status===401){setAuth(true);throw new Error(credential.current?'접근 암호가 맞지 않아요. 다시 확인해 주세요.':'공유받은 접근 암호를 입력해 주세요.');}if(!res.ok)throw new Error('기록을 불러오지 못했어요. 다시 시도해 주세요.');const data=await res.json() as {records:Day[];canEdit:boolean};setRecords(data.records);setDay(data.records.find((d:Day)=>d.date===(ready?day.date:today()))||blank(ready?day.date:today()));setCanEdit(data.canEdit);if(!ready&&!data.canEdit)setView('overview');setAuth(false);setAccessCode('');setReady(true);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 useEffect(()=>{const fn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn);},[dirty]);
 function edit(p:Partial<Day>){setDay(d=>({...d,...p}));setDirty(true);setSaved(false);setError('');}
 function sessionChange(i:number,key:'pain'|'minutes',value:string,j?:number){edit({sessions:day.sessions.map((s,n)=>n!==i?s:key==='pain'?{...s,pain:value}:{...s,minutes:s.minutes.map((v,k)=>k===j?value:v)})});}
 async function save(){if(!dirty)return true;if(!canEdit)return false;if(!validDay(day)){setError('통증은 0~5, 운동 시간은 0~1440분 사이로 입력해 주세요. 소수점은 한 자리까지 가능해요.');return false;}setSaving(true);setError('');try{const res=await fetch(`${apiBase}/api/records`,{method:'PUT',headers:{...authHeaders(),'Content-Type':'application/json'},body:JSON.stringify(day)});const data=await res.json() as {record:Day;error?:string};if(!res.ok)throw new Error(data.error||'저장하지 못했어요. 입력 내용은 그대로 있으니 다시 시도해 주세요.');setDay(data.record);setRecords(r=>[...r.filter(d=>d.date!==day.date),data.record].sort((a,b)=>a.date.localeCompare(b.date)));setDirty(false);setSaved(true);return true;}catch(e){setError((e as Error).message);return false;}finally{setSaving(false);}}
 async function chooseDate(date:string){if(!date||saving||!ready||date===day.date)return;if(!await save())return;setDay(records.find(d=>d.date===date)||blank(date));setSaved(false);setError('');}
 function shiftDate(n:number){const d=new Date(`${day.date}T12:00:00`);d.setDate(d.getDate()+n);chooseDate(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`);}
 async function changeView(v:string){if(saving||!await save())return;setView(v);}
 const pain=painRange(day);const maxMinutes=Math.max(30,...records.map(total));
 const bridge=useRef({save,day,ready,saving});bridge.current={save,day,ready,saving};
 useEffect(()=>{
  const ctx=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;
  if(!ctx?.registerTool)return;const lifecycle=new AbortController();
  try{Promise.resolve(ctx.registerTool({name:'save_current_daily_record',title:'현재 날짜 기록 저장',description:'현재 화면에 입력된 통증, 운동 시간, 활동, 특이사항을 저장합니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('입력 인자는 필요하지 않습니다.');const state=bridge.current;if(!state.ready||state.saving)throw new Error('지금은 저장할 수 없습니다.');if(!await state.save())throw new Error('저장에 실패했습니다. 화면의 오류를 확인해 주세요.');return {saved:true,date:state.day.date};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();
 },[]);
 if(!ready)return <main className="access-shell"><div className="access-brand"><Activity size={28}/><h1>통증 운동 기록</h1></div><section className="access-card"><LockKeyhole size={28}/><h2>함께 보는 하루 기록</h2><p>공유받은 접근 암호를 입력해 주세요.</p><form onSubmit={e=>{e.preventDefault();load(accessCode);}}><label htmlFor="access-code">접근 암호</label><input id="access-code" type="password" autoComplete="off" autoCapitalize="none" spellCheck={false} value={accessCode} onChange={e=>setAccessCode(e.target.value)} disabled={loading} required/><button className="save-button" disabled={loading||!accessCode.trim()}>{loading?'연결 확인 중…':'기록 열기'}</button></form>{error&&<p role="alert" className="access-error">{error}</p>}{!apiBase&&<a href="/signin-with-chatgpt?return_to=/" target="_top">본인 계정으로 로그인</a>}<p className="access-hint">암호는 가족에게만 공유해 주세요.</p></section></main>;
 return <main className="journal-shell"><header className="masthead"><a className="brand" href="./"><span className="brand-icon"><Activity size={23}/></span><span>통증 운동 기록<span className="brand-caption">DAILY MOVEMENT JOURNAL</span></span></a><div className="access-actions"><span className="access-badge">{canEdit?'입력·수정 가능':'가족 보기 전용'}</span><button aria-label="최신 기록 불러오기" disabled={loading||dirty||saving} onClick={()=>load()}><RefreshCw size={17}/></button><button aria-label="잠금" disabled={dirty||saving} onClick={()=>{credential.current='';setReady(false);setCanEdit(false);setRecords([]);setDay(blank(today()));setError('');}}><LogOut size={17}/></button></div></header>
 <Tabs value={view} onValueChange={changeView}><div className="page-heading"><div><span className="eyebrow">MY DAILY CHECK-IN</span><h1>{view==='daily'?'오늘의 몸을 기록해요':'차곡차곡 쌓인 변화'}</h1><p>{view==='daily'?'통증과 운동, 하루 세 번 가볍게 남겨요.':'날짜별 통증 범위와 운동 시간을 살펴보세요.'}</p></div><TabsList className="view-tabs"><TabsTrigger value="daily"><CalendarDays/>하루 기록</TabsTrigger><TabsTrigger value="overview"><ChartNoAxesCombined/>전체보기</TabsTrigger></TabsList></div>
 {error&&<div className="error-box" role="alert">{error}</div>}
 <TabsContent value="daily"><section className="date-strip"><div className="date-navigation"><button aria-label="이전 날짜" onClick={()=>shiftDate(-1)} disabled={saving||!ready}><ArrowLeft size={19}/></button><div><label htmlFor="record-date">기록 날짜</label><input id="record-date" type="date" value={day.date} onChange={e=>chooseDate(e.target.value)} disabled={saving||!ready}/></div><button aria-label="다음 날짜" onClick={()=>shiftDate(1)} disabled={saving||!ready}><ArrowRight size={19}/></button><button className="today-button" onClick={()=>chooseDate(today())} disabled={saving||!ready}>오늘</button></div><div className="day-summary"><span>통증 범위<strong>{pain?`${pain[0]} – ${pain[1]}`:'—'}</strong></span><span>운동 합계<strong>{total(day)}<small> 분</small></strong></span></div></section>
 <fieldset disabled={saving||loading||!ready||!canEdit} className="entry-fields"><legend className="sr-only">{dateLabel(day.date)} 기록</legend><div className="session-grid">{periods.map((name,i)=>{const Icon=icons[i];return <section className={`session-card period-${i}`} key={name}><div className="session-heading"><span className="period-icon"><Icon size={23}/></span><h2>{name}</h2><span className="period-number">0{i+1}</span></div><label className="pain-label" htmlFor={`pain-${i}`}>통증<span>0–5</span></label><div className="pain-input"><input id={`pain-${i}`} aria-label={`${name} 통증`} type="number" inputMode="decimal" min="0" max="5" step="0.1" placeholder="—" value={day.sessions[i].pain} onChange={e=>sessionChange(i,'pain',e.target.value)}/><span>/ 5</span></div><div className="pain-guide"><span>통증 없음 0</span><span>매우 심함 5</span></div><div className="exercise-heading"><span>운동 시간</span><span>분</span></div><div className="exercise-list">{exercises.map((name,j)=><label key={name} className="exercise-row"><span>{name}</span><input aria-label={`${periods[i]} ${name} 시간 (분)`} type="number" inputMode="decimal" min="0" max="1440" step="0.1" placeholder="—" value={day.sessions[i].minutes[j]} onChange={e=>sessionChange(i,'minutes',e.target.value,j)}/></label>)}</div><div className="session-total"><Clock3 size={15}/><span>{name} 운동</span><strong>{Math.round(day.sessions[i].minutes.reduce((s,m)=>s+Number(m||0),0)*10)/10}분</strong></div></section>})}</div>
 <div className="details-grid"><section className="detail-card"><div className="section-title"><Footprints size={21}/><h2>오늘의 활동</h2><span>여러 개 선택 가능</span></div><div className="activity-options">{activities.map(a=><label className={`activity-chip ${day.activities.includes(a)?'selected':''}`} key={a}><Checkbox disabled={saving||loading||!ready||!canEdit} checked={day.activities.includes(a)} onCheckedChange={checked=>edit({activities:checked?[...day.activities,a]:day.activities.filter(v=>v!==a)})}/><span>{a}</span></label>)}</div><label className="custom-label" htmlFor="custom-activity">직접 입력</label><input id="custom-activity" className="text-input" maxLength={500} placeholder="그 밖에 어떤 활동을 했나요?" value={day.customActivity} onChange={e=>edit({customActivity:e.target.value})}/></section><section className="detail-card"><div className="section-title"><NotebookPen size={21}/><h2>특이사항</h2><span>선택</span></div><textarea aria-label="특이사항" maxLength={5000} placeholder="몸 상태, 약 복용 등 기억해 둘 내용을 남겨요." value={day.notes} onChange={e=>edit({notes:e.target.value})}/></section></div></fieldset>
 {canEdit&&<footer className="save-bar"><div role="status" aria-live="polite">{loading?'기록을 불러오는 중…':saving?'저장하는 중…':saved?<><Check size={18}/>저장했어요</>:dirty?'변경한 내용이 있어요':'빈칸은 미기록으로 남겨요.'}</div><button className="save-button" onClick={save} disabled={!dirty||saving||!ready}><Save size={18}/>{saving?'저장 중…':'기록 저장'}</button></footer>}</TabsContent>
 <TabsContent value="overview"><div className="overview-heading"><span>전체 <strong>{records.length}일</strong>의 기록</span><span>날짜를 누르면 해당 기록으로 이동해요.</span></div>{records.length===0?<section className="empty-records"><Bike size={42}/><h2>첫 기록을 기다리고 있어요</h2><p>하루 기록을 저장하면 여기에 변화가 쌓여요.</p><button onClick={()=>setView('daily')}>하루 기록하기<ArrowRight size={17}/></button></section>:<div className="chart-grid"><section className="chart-card"><div className="section-title"><Activity size={21}/><h2>일자별 통증 범위</h2></div><p className="chart-description">아침·오후·밤의 최솟값부터 최댓값까지</p><div className="chart-axis"><span>날짜</span><div>{[0,1,2,3,4,5].map(n=><span key={n}>{n}</span>)}</div><span>범위</span></div>{records.map(record=>{const r=painRange(record);return <button className="chart-row" key={record.date} onClick={()=>{setDay(record);setSaved(false);setView('daily');}} aria-label={`${dateLabel(record.date)}, 통증 ${r?r.join('~'):'미기록'}, 기록 열기`}><span className="chart-date">{record.date.slice(2).replaceAll('-','.')}</span><span className="bar-track pain-track">{r&&<span className="range-bar" style={{left:`${r[0]*20}%`,width:`${(r[1]-r[0])*20}%`}}><i/><i/></span>}</span><span className="chart-value">{r?r[0]===r[1]?r[0]:`${r[0]}–${r[1]}`:'미기록'}</span></button>})}</section><section className="chart-card minutes-chart"><div className="section-title"><Clock3 size={21}/><h2>하루 운동 시간</h2><span>분</span></div><p className="chart-description">세 가지 운동의 아침·오후·밤 시간 합계</p><div className="chart-axis activity-axis"><span>날짜</span><div>{[0,.25,.5,.75,1].map(n=><span key={n}>{Math.round(maxMinutes*n)}</span>)}</div><span>합계</span><span>추가 활동</span></div>{records.map(record=><button className="chart-row activity-row" key={record.date} onClick={()=>{setDay(record);setSaved(false);setView('daily');}} aria-label={`${dateLabel(record.date)}, 운동 ${total(record)}분, 기록 열기`}><span className="chart-date">{record.date.slice(2).replaceAll('-','.')}</span><span className="bar-track"><span className="minutes-bar" style={{width:`${total(record)/maxMinutes*100}%`}}/></span><span className="chart-value">{record.sessions.every(s=>s.minutes.every(m=>m===''))?'미기록':`${total(record)}분`}</span><span className="activity-summary">{record.activities.length>0&&<span className="activity-tags">{record.activities.map(a=><span key={a}>{a}</span>)}</span>}{record.customActivity&&<span className="activity-detail">{record.customActivity}</span>}{!record.activities.length&&!record.customActivity&&<span className="no-activity">—</span>}</span></button>)}</section></div>}<p className="overview-note">운동 시간은 누워서 브릿지·경사블럭·다리들기의 입력 시간만 합산해요. 활동 체크 항목은 합산하지 않아요.</p></TabsContent></Tabs><footer className="page-footer"><Activity size={15}/>통증 운동 기록<span>하루하루, 내 몸의 변화를 알아가는 시간</span></footer></main>;
}



